source 'https://rubygems.org'

ruby '2.1.2'

gem 'bootstrap-sass', '~> 3.1'
gem 'builder', '~> 3.0'
gem 'font-awesome-middleman', '~> 4.1'
gem 'middleman', '~> 3.3.0'
gem 'middleman-blog'
gem 'middleman-bootstrap-navbar', '~> 2.0'
gem 'middleman-imageoptim', '~> 0.1.4'
gem 'middleman-livereload', '~> 3.3.0'
gem 'middleman-slim', '~> 0.1'
gem 'middleman-syntax'
gem 'nokogiri'
gem 'redcarpet'
